### ISSUE TITLE
Add torrent not working

### ISSUE THREAD

**Issue by tanharoh** [edavis/transmission-fluid#8]
`client('torrent-add', filename="/home/ubuntu/9.torrent")`

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/transmission/__init__.py", line 51, in __call__
    return self._deserialize_response(response)
  File "/usr/local/lib/python2.7/dist-packages/transmission/__init__.py", line 80, in _deserialize_response
    raise BadRequest("Request failed: '%s'" % doc['result'])
transmission.BadRequest: Request failed: 'invalid or corrupt torrent file'`

**Comment by edavis** [comment]
Does 9.torrent work when adding directly to Transmission? Do all torrents fail when added through transmission-fluid?

**Comment by aburdulescu** [comment]
I get the same error when trying to add a torrent.

I tried to add the same torrent with transmission-remote and it works.

I had a look at the HTTP request sent by transmission-remote and it looks like this:
```json
{
    "arguments": {
        "metainfo": "alallalalalallalalal"
    },
    "method": "torrent-add",
    "tag": 8
}
```

The "metainfo" argument is the "base64-encoded .torrent content" (from https://raw.githubusercontent.com/transmission/transmission/master/extras/rpc-spec.txt).

So, if you do something like this:
```python
tr = transmission.Transmission()
with open('/path/to/file', 'rb') as f:
    metainfo = base64.b64encode(f.read())
    r = tr('torrent-add', metainfo=metainfo)
```

it should work.

**Comment by edavis** [comment]
@aburdulescu Interesting... rpc-spec.txt still lists `filename` as a valid request argument, so not sure why adding torrents that way wouldn't work. Unless the spec and the client code have fallen out of sync and only base64-encoded content works now.

At this point, I can't think of any changes to be made to transmission-fluid that would alleviate the problem. Maybe a note in the docs?

**Comment by aburdulescu** [comment]
@edavis I think that the spec is not very clear how the `filename` argument works.
The spec says: `"filename"           | string      filename or URL of the .torrent file`.
So, from this description is intuitive to understand that both of the following requests should work:
```json
{
    "arguments": {
        "filename": "/path/to/some/local/file"
    },
    "method": "torrent-add",
}
```
```json
{
    "arguments": {
        "filename": "some_url_to_a_torrent_file"
    },
    "method": "torrent-add",
}
```
However, after having a look at the [transmission-remote code](https://github.com/transmission/transmission/blob/1b36e34d9bcfd8ea28f2c6ff4085a294e4cf0f71/daemon/remote.c#L2291) and [rpc-server code](https://github.com/transmission/transmission/blob/1b36e34d9bcfd8ea28f2c6ff4085a294e4cf0f71/libtransmission/rpc-server.c#L227), I don't think both requests are valid. Only the one specifying a url for filename is valid.

`transmission-remote` takes the file and encodes it into base64 and sends the encoded data using the `metainfo` argument. It does not send the file path to the daemon(which is kind of logical if you take into consideration that the daemon may run on a different machine than the RPC client).

I agree with you, transmission-fluid shouldn't make any changes but I think a issue should be submitted to Transmission to modify the Transmission RPC spec(to make clear how the `filename` argument works).

Also, a note in the docs can't hurt .

**Comment by edavis** [comment]
@aburdulescu Thanks for digging into this. Great write-up.
